/*CREATED IN NETBEANS: JAVA GUI WITH CHATBOT
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myPackage;

/**
 *
 * @author Jessicab
 */
import java.awt.Desktop;
import java.net.URI;

public class NewJFrame extends javax.swing.JFrame {
    private double total = 0.0;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup2 = new javax.swing.ButtonGroup();
        shopName = new javax.swing.JLabel();
        oneVanilla = new javax.swing.JRadioButton();
        oneStrawberry = new javax.swing.JRadioButton();
        twoVanilla = new javax.swing.JRadioButton();
        twoStrawberry = new javax.swing.JRadioButton();
        mixedScoops = new javax.swing.JRadioButton();
        chooseScoop = new javax.swing.JLabel();
        orderBtn = new javax.swing.JButton();
        addNuts = new javax.swing.JCheckBox();
        addCherries = new javax.swing.JCheckBox();
        totalCalc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chatBot = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IceCreamOrder");
        setBackground(new java.awt.Color(235, 221, 223));

        shopName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        shopName.setForeground(new java.awt.Color(175, 101, 126));
        shopName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopName.setText("Sanderson’s Ice Cream Sundaes!");
        shopName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        oneVanilla.setText("($2.20)  1 Scoop Vanilla");
        oneVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneVanillaActionPerformed(evt);
            }
        });

        oneStrawberry.setText("($2.20)  1 Scoop Strawberry");
        oneStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStrawberryActionPerformed(evt);
            }
        });

        twoVanilla.setText("($3.00)   2 Scoops Vanilla");
        twoVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoVanillaActionPerformed(evt);
            }
        });

        twoStrawberry.setText("($3.00)   2 Scoops Strawberry");
        twoStrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoStrawberryActionPerformed(evt);
            }
        });

        mixedScoops.setText("($3.00)  1 Scoop Vanilla + 1 Scoop Strawberry");
        mixedScoops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixedScoopsActionPerformed(evt);
            }
        });

        chooseScoop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chooseScoop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseScoop.setText("Create your Sundae!");

        orderBtn.setBackground(new java.awt.Color(255, 209, 223));
        orderBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orderBtn.setText("Order Sundae!");
        orderBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        addNuts.setText("($0.50) Add  Nuts");
        addNuts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNuts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addNutsItemStateChanged(evt);
            }
        });

        addCherries.setText("($0.50) Add Cherries");
        addCherries.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addCherriesItemStateChanged(evt);
            }
        });

        totalCalc.setBackground(new java.awt.Color(242, 230, 234));
        totalCalc.setText("$#.##");
        totalCalc.setToolTipText("");
        totalCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCalcActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(240, 225, 230));
        jLabel1.setText("Total:");

        chatBot.setBackground(new java.awt.Color(255, 209, 223));
        chatBot.setText("Chatbot");
        chatBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatBotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oneStrawberry)
                            .addComponent(oneVanilla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNuts)
                            .addComponent(addCherries))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chooseScoop)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(twoVanilla)
                                .addComponent(twoStrawberry)
                                .addComponent(mixedScoops)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(60, 60, 60)
                        .addComponent(chatBot)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(shopName)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shopName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseScoop)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(oneVanilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneStrawberry)
                            .addComponent(addCherries)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addNuts)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoVanilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twoStrawberry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mixedScoops)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chatBot)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>                        

    private void oneVanillaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
oneVanilla.setSelected(true);
oneStrawberry.setSelected(false);
twoVanilla.setSelected(false);
twoStrawberry.setSelected(false);
mixedScoops.setSelected(false);

    }                                          

    private void oneStrawberryActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
oneVanilla.setSelected(false);
oneStrawberry.setSelected(true);
twoVanilla.setSelected(false);
twoStrawberry.setSelected(false);
mixedScoops.setSelected(false);

    }                                             

    private void twoVanillaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
oneVanilla.setSelected(false);
oneStrawberry.setSelected(false);
twoVanilla.setSelected(true);
twoStrawberry.setSelected(false);
mixedScoops.setSelected(false);

    }                                          

    private void twoStrawberryActionPerformed(java.awt.event.ActionEvent evt) {                                              
oneVanilla.setSelected(false);
oneStrawberry.setSelected(false);
twoVanilla.setSelected(false);
twoStrawberry.setSelected(true);
mixedScoops.setSelected(false);

    }                                             

    private void mixedScoopsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
oneVanilla.setSelected(false);
oneStrawberry.setSelected(false);
twoVanilla.setSelected(false);
twoStrawberry.setSelected(false);
mixedScoops.setSelected(true);

    }                                           

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         double total = 0;
        
        if (oneVanilla.isSelected() || oneStrawberry.isSelected())
        {
            total += 2.20;
        }else if(twoVanilla.isSelected() || twoStrawberry.isSelected() || mixedScoops.isSelected())
        {

            total += 3;
        }
         if (addNuts.isSelected())
        {
            total += 0.50;
        }

        if (addCherries.isSelected()) {
            total += 0.50;
    }
                totalCalc.setText("$" + String.format("%.2f", total));

    }                                        

    private void addNutsItemStateChanged(java.awt.event.ItemEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void addCherriesItemStateChanged(java.awt.event.ItemEvent evt) {                                             
    }                                            

    private void totalCalcActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void chatBotActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        try{
        //create URI object with URL from copilot
        URI url = new URI("https://sandersonsai.ai.copilot.live");
        if (Desktop.isDesktopSupported()){
            //check if Desktop is supported
            Desktop desktop = Desktop.getDesktop();
            //check if browser action is supported
            if (desktop.isSupported(Desktop.Action.BROWSE)){
                desktop.browse(url);
            }else {
                System.out.println("BROWSE action not supported.");
            }
        }else{
            System.out.println("Desktop not supported.");
        } 
        } catch (Exception e){
            e.printStackTrace();
        }
    }                                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox addCherries;
    private javax.swing.JCheckBox addNuts;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton chatBot;
    private javax.swing.JLabel chooseScoop;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton mixedScoops;
    private javax.swing.JRadioButton oneStrawberry;
    private javax.swing.JRadioButton oneVanilla;
    private javax.swing.JButton orderBtn;
    private javax.swing.JLabel shopName;
    private javax.swing.JTextField totalCalc;
    private javax.swing.JRadioButton twoStrawberry;
    private javax.swing.JRadioButton twoVanilla;
    // End of variables declaration                   
}
